"""empty message

Revision ID: 446451c6c5a3
Revises: c4a89fe86744
Create Date: 2019-02-01 11:15:25.804601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446451c6c5a3'
down_revision = 'c4a89fe86744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placanje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potvrda', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('izlet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izlet_id'], ['izlet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'izlet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'izlet', type_='foreignkey')
    op.drop_table('placanje')
    # ### end Alembic commands ###
