"""empty message

Revision ID: 53a0edbc9feb
Revises: ddb7d8dd89be
Create Date: 2019-02-01 09:26:11.694452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a0edbc9feb'
down_revision = 'ddb7d8dd89be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    op.add_column('izlet', sa.Column('lat', sa.Numeric(), nullable=True))
    op.add_column('izlet', sa.Column('lng', sa.Numeric(), nullable=True))
    op.create_foreign_key(None, 'izlet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'izlet', type_='foreignkey')
    op.drop_column('izlet', 'lng')
    op.drop_column('izlet', 'lat')
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
