"""empty message

Revision ID: 5bc81970dd50
Revises: 3e0c2aa0ac26
Create Date: 2019-01-31 12:26:24.581757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc81970dd50'
down_revision = '3e0c2aa0ac26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'izlet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'izlet', type_='foreignkey')
    op.drop_column('izlet', 'user_id')
    # ### end Alembic commands ###
