"""empty message

Revision ID: c4228d1a2913
Revises: f9b7e51cfa43
Create Date: 2019-01-31 15:10:27.921660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4228d1a2913'
down_revision = 'f9b7e51cfa43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'izlet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'izlet', type_='foreignkey')
    # ### end Alembic commands ###
